# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frames.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frames.proto',
  package='frames',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x66rames.proto\x12\x06\x66rames\"\x96\x01\n\x0eMousePositions\x12\x37\n\tpositions\x18\x01 \x03(\x0b\x32$.frames.MousePositions.MousePosition\x1aK\n\rMousePosition\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\r\x12\t\n\x01y\x18\x03 \x01(\r\x12\n\n\x02sx\x18\x04 \x01(\x05\x12\n\n\x02sy\x18\x05 \x01(\x05\",\n\x04\x41rcs\x12$\n\x04\x61rcs\x18\x01 \x03(\x0b\x32\x16.frames.MousePositions\"\x1c\n\x0c\x44roppedFrame\x12\x0c\n\x04time\x18\x01 \x01(\x01'
)




_MOUSEPOSITIONS_MOUSEPOSITION = _descriptor.Descriptor(
  name='MousePosition',
  full_name='frames.MousePositions.MousePosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='frames.MousePositions.MousePosition.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='frames.MousePositions.MousePosition.x', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='frames.MousePositions.MousePosition.y', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sx', full_name='frames.MousePositions.MousePosition.sx', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sy', full_name='frames.MousePositions.MousePosition.sy', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=175,
)

_MOUSEPOSITIONS = _descriptor.Descriptor(
  name='MousePositions',
  full_name='frames.MousePositions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='frames.MousePositions.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MOUSEPOSITIONS_MOUSEPOSITION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=175,
)


_ARCS = _descriptor.Descriptor(
  name='Arcs',
  full_name='frames.Arcs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arcs', full_name='frames.Arcs.arcs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=221,
)


_DROPPEDFRAME = _descriptor.Descriptor(
  name='DroppedFrame',
  full_name='frames.DroppedFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='frames.DroppedFrame.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=251,
)

_MOUSEPOSITIONS_MOUSEPOSITION.containing_type = _MOUSEPOSITIONS
_MOUSEPOSITIONS.fields_by_name['positions'].message_type = _MOUSEPOSITIONS_MOUSEPOSITION
_ARCS.fields_by_name['arcs'].message_type = _MOUSEPOSITIONS
DESCRIPTOR.message_types_by_name['MousePositions'] = _MOUSEPOSITIONS
DESCRIPTOR.message_types_by_name['Arcs'] = _ARCS
DESCRIPTOR.message_types_by_name['DroppedFrame'] = _DROPPEDFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MousePositions = _reflection.GeneratedProtocolMessageType('MousePositions', (_message.Message,), {

  'MousePosition' : _reflection.GeneratedProtocolMessageType('MousePosition', (_message.Message,), {
    'DESCRIPTOR' : _MOUSEPOSITIONS_MOUSEPOSITION,
    '__module__' : 'frames_pb2'
    # @@protoc_insertion_point(class_scope:frames.MousePositions.MousePosition)
    })
  ,
  'DESCRIPTOR' : _MOUSEPOSITIONS,
  '__module__' : 'frames_pb2'
  # @@protoc_insertion_point(class_scope:frames.MousePositions)
  })
_sym_db.RegisterMessage(MousePositions)
_sym_db.RegisterMessage(MousePositions.MousePosition)

Arcs = _reflection.GeneratedProtocolMessageType('Arcs', (_message.Message,), {
  'DESCRIPTOR' : _ARCS,
  '__module__' : 'frames_pb2'
  # @@protoc_insertion_point(class_scope:frames.Arcs)
  })
_sym_db.RegisterMessage(Arcs)

DroppedFrame = _reflection.GeneratedProtocolMessageType('DroppedFrame', (_message.Message,), {
  'DESCRIPTOR' : _DROPPEDFRAME,
  '__module__' : 'frames_pb2'
  # @@protoc_insertion_point(class_scope:frames.DroppedFrame)
  })
_sym_db.RegisterMessage(DroppedFrame)


# @@protoc_insertion_point(module_scope)
